# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Scrape Civil Service Jobs

on:
  workflow_dispatch:
    inputs:
      limitPages:
        description: 'Limit number of pages fetched'
        required: false
        type: number
      limitJobs:
        description: 'Limit number of jobs fetched'
        required: false
        type: number

# As of 19/2/2025 the scraper is no longer working. Civil Service Jobs have implemented a captcha on every request which means 
# this scraping process no longer works. If anyone from Civil Service Jobs is reading this please get in touch I'd love to discuss
# how we could make available a permanent archive public job ads (which are published under open government liceneses). You can contact me
# by email on david at davidheath dot org. 

#  schedule:
#    # Run daily at 02:03
#    - cron: "03 02 * * *"

permissions:
  id-token: write
  contents: write

jobs:
  scrape-jobs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@d781c1b4ed31764801bfae177617bb0446f5ef8d # v1.218.0
      with:
        ruby-version: 3.3.4
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically

    - name: Authenticate to AWS using OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::542188523718:role/github_action_role
        aws-region: eu-west-1

    - name: Run scraper
      run: bundle exec ruby ./scraper.rb --line-logger ${{ inputs.limitPages > 0 && format('--limit-pages {0}', inputs.limitPages) }}  -d csj.sqlite

    - name: Run transfer script
      run: bundle exec ruby ./bin/transfer_data_to_gsheet
      env:
        GOOGLE_CLOUD_CREDS: ${{ secrets.GOOGLE_CLOUD_CREDS }}
