# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Scrape Civil Service Jobs

on:
  workflow_dispatch:
    inputs:
      limitPages:
        description: 'Limit number of pages fetched'
        required: false
        type: number
      limitJobs:
        description: 'Limit number of jobs fetched'
        required: false
        type: number

  schedule:
    # Run daily at 02:03
    - cron: "03 02 * * *"

permissions:
  id-token: write
  contents: write

jobs:
  scrape-jobs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@a6e6f86333f0a2523ece813039b8b4be04560854 # v1.190.0
      with:
        ruby-version: 3.3.4
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically

    - name: Authenticate to AWS using OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::542188523718:role/github_action_role
        aws-region: eu-west-1

    - name: Download from s3
      run: bundle exec ruby ./download_from_s3.rb

    - name: Extract job database from tgz
      uses: a7ul/tar-action@ed9cbd44fc9276db29ea2fb1f8adf3d7e0691589
      id: extract
      with:
        command: x
        cwd: ./
        files: csj.tar.gz

    - name: Run scraper
      run: bundle exec ruby ./scraper.rb --line-logger ${{ inputs.limitPages > 0 && format('--limit-pages {0}', inputs.limitPages) }}  -d csj.sqlite

    - name: Compress job database to tgz
      uses: a7ul/tar-action@ed9cbd44fc9276db29ea2fb1f8adf3d7e0691589
      id: compress
      with:
        command: c
        cwd: ./
        files: |
          ./csj.sqlite
        outPath: csj.tar.gz

    - name: Push file to s3
      run: bundle exec ruby ./upload_to_s3.rb
  