# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Scrape Civil Service Jobs

on:
  workflow_dispatch:
    inputs:
      limitPages:
        description: 'Limit number of pages fetched'
        required: false
        type: number
      limitJobs:
        description: 'Limit number of jobs fetched'
        required: false
        type: number

  schedule:
    # Run daily at 02:03
    - cron: "03 02 * * *"

permissions:
  id-token: write
  contents: write

jobs:
  scrape-jobs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run tar command
      run: |
        tar zcf example.tgz scraper.rb
        ls -l example.tgz
